#!/bin/sh
# postinst script for #PACKAGE#

set -e

case "$1" in
    configure)
        chmod u+x /etc/skel/Desktop/siduction-irc.desktop
        for i in /home/*/Desktop/siduction-irc.desktop; do
            if [ -h $i ]; then
                BASENAME=$(basename $i)
                if [ -e /etc/skel/Desktop/siduction-irc.desktop ]; then
                    DIRNAME=$(dirname $i)
                    rm -f $i
                    cp /etc/skel/Desktop/siduction-irc.desktop $DIRNAME
                    USER=$(ls -ld $DIRNAME | awk '{print $3}')
                    chown "$USER:$USER" $i
                fi
            fi
        done
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
